server:
  port: 8080

spring:
  datasource:
    username: yinshi
    password: 123
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  redis:
    database: 0
    host: 192.168.3.33
    password: 123
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10000


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

